// Generated by Lekko. DO NOT EDIT.
package lekko

import (
	"context"

	lekkoconfigs "example/lekko/configs"
	lekkoexample "example/lekko/example"
	client "github.com/lekkodev/go-sdk/client"
)

type LekkoClient struct {
	Configs *lekkoconfigs.LekkoClient
	Example *lekkoexample.LekkoClient
	Close   client.CloseFunc
}

// Initializes the Lekko SDK client.
// For remote configs to be fetched correctly, the LEKKO_API_KEY env variable is required.
// If the env variable is missing or if there are any connection errors, the static fallbacks will be used.
func NewLekkoClient(ctx context.Context, opts ...client.ProviderOption) *LekkoClient {
	repoOwner := "passichenko-lekko-3"
	repoName := "lekko-configs"
	cli, close := client.NewClientFromEnv(ctx, repoOwner, repoName, opts...)
	return &LekkoClient{
		Configs: &lekkoconfigs.LekkoClient{Client: cli},
		Example: &lekkoexample.LekkoClient{Client: cli},
		Close:   close,
	}
}
