// Generated by Lekko. DO NOT EDIT.
package lekkoconfigs

import (
	"context"
	"errors"

	"github.com/lekkodev/go-sdk/client"
	"github.com/lekkodev/go-sdk/pkg/debug"
)

type LekkoClient struct {
	client.Client
}

func (c *LekkoClient) GetText() string {
	ctx := context.Background()

	result, err := c.GetString(ctx, "configs", "text")
	if err == nil {
		return result
	}
	result = getText()
	if !errors.Is(err, client.ErrNoOpProvider) {
		debug.LogError("Lekko evaluation error", "name", "configs/text", "err", err)
	}
	debug.LogDebug("Lekko fallback", "name", "configs/text", "result", result)
	return result
}
